# Generated by Django 5.0.1 on 2024-11-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='admin', max_length=255, null=True),
        ),
    ]
